### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by y-naga0926** [y-naga0926/furima-31972#9]
# 本番環境(Heroku)のURL
[https://furima-31972.herokuapp.com/](url)
# Basic認証のIDとパスワード
ID: admin
password: 2222
# 出品者用のメールアドレスとパスワード
email: test5@example
password: test5555
# 購入者用のメールアドレスとパスワード
email: test4@example
password: test4444
# 購入用カードの番号・期限・セキュリティコード
番号: 4242424242424242
期限:3月23年
セキュリティコード: 123

よろしくお願い致します！

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/117903592-d0db2600-b30a-11eb-82ee-f02cbb4d55ed.png)
